CREDITBYPAN = 'CREDITBYPAN'
CREDITBYTOKEN = 'CREDITBYTOKEN'
CREDITBYCARDID = 'CREDITBYCARDID'
CREDITBYACCOUNT = 'CREDITBYACCOUNT'

DEBITBYPAN = 'DEBITBYPAN'
DEBITBYTOKEN = 'DEBITBYTOKEN'
DEBITBYCARDID = 'DEBITBYCARDID'
DEBITBYACCOUNT = 'DEBITBYACCOUNT'

PURCHASEBYPAN = 'PURCHASEBYPAN'
PURCHASEBYTOKEN = 'PURCHASEBYTOKEN'
PURCHASEBYACCOUNT = 'PURCHASEBYACCOUNT'
PURCHASEBYCARDID = 'PURCHASEBYCARDID'

REVERSE = 'REVERSE'
